### DISCUSSION TITLE
release 0.11.1-dev

### DISCUSSION THREAD

**Discussion by Nik71git** [maxill1/ialarm-mqtt#37] [Q&A]
Buongiorno a tutti, secondo me conviene concentrarci sulla versione dev in modo che poi diventi stable con i miglioramenti implementati. Per pulizia di installazione ho rimosso la stable 0.10, ho eliminato i sensori, con mqtt-explorer ho eliminato i payload ed i relativi topic della vecchia installazione, ho riavviato il tutto ed ho installato la release dev in quanto i sensori riportavano nelle info la vecchia release 0.10.

**Domanda 1**:  i sensori conviene crearli "a mano" su Home Assistant ?? Al momento non me ne rileva nemmeno uno ma credo perchè ancora non hanno cambiato stato (tutto chiuso e pannello armato

**Domanda 2**: dalla config è sparito _polling_events_ è normale?

**Comment by maxill1** [comment]
1) no sarebbero dovuti apparire, forse è lo stesso problema di cache riportato da altri 
2) giusto non ci sia, gli **eventi non li prendiamo più in polling** da GetLog ma dalle "**push** notifications" che spontaneamente invia via TCP il pannello (in real time)

**Reply by gideonklein** [reply]
Seguo con interesse

**Reply by maxill1** [reply]
ho un dubbio, che intendevi con "i sensori conviene crearli "a mano" su Home Assistant"?

**Reply by Nik71git** [reply]
tipo` così

```
- sensor:
    platform: mqtt
    id: zona1
    name: camera
    payload
    topic
    ecc. ecc.
```

in configuration.yaml

**Reply by Nik71git** [reply]
@maxill1 mi è venuto in mente che Home Assistant ha implementato la nuova sintassi per mqtt, cioè se voglio creare a mano un sensore devo usare la nuova platform, vedi esempio sotto:

```
mqtt:
  sensor:
    - name: "RSSI"
      state_topic: "home/sensor1/infojson"
      unit_of_measurement: "dBm"
      value_template: "{{ value_json.RSSI }}"
      availability:
        - topic: "home/sensor1/status"
      payload_available: "online"
      payload_not_available: "offline"
      json_attributes_topic: "home/sensor1/attributes
```

e non più con la vecchia notazione:

```
sensor:
    platform: mqtt
    id: <id_sensore>
    name: <nome_sensore>
    topic:
    payload:
```

il fatto che i sensori non compaiono con l'integrazione può dipendere da questo fatto?
