### ISSUE TITLE
Notification of last event, sensor.last_event, not correct. The message received contains the text of the last but one event.

### ISSUE THREAD

**Issue by maurizioandreotti60** [maxill1/ialarm-mqtt#25]
Ciao, ho creato una automazione, come da tua documentazione, per inviare una notifica con l'ultimo evento, ma il messaggio iinviato contiene il testo del penultimo evento.
Questa l'automazione
```
- id: '1638118438572'
  alias: Eventi Antifurto
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.last_event
    id: Eventi Antifurto
  condition: []
  action:
  - service: notify.maurizio_telegram
    data:
      message: 'Notifica dall''antifurto: da {{ trigger.from_state.state }} a {{ trigger.to_state.state
        }}'
  mode: single
```
Il messaggio Telegram che mi arriva è:
"Notifica dall'antifurto: da Bypass recovery (zone 2 PIR Cucina) a Bypass recovery (zone 2 PIR Cucina)"
In pratica trigger.to_state.state mi ritorna lo stato precedente e non quello attuale.
La centrale è di Casasicura.
